name       : serve-d
version    : 0.8.0.14
release    : 5
source     :
    - git|https://github.com/Pure-D/serve-d.git : 482c054f978e8e192bdc2cb343efee7ca52963e7
license    : MIT
component  : programming.tools
summary    : D LSP server (dlang language server protocol server)
description: |
    Microsoft language server protocol implementation for D. This program is the heart of code-d and implements most IDE features in D. The purpose of this project is to give every editor the same capabilities and editing features as code-d through the widely available Microsoft Language Server Protocol (LSP).
networking : yes
builddeps  :
    - dub
    - ldc
rundeps    :
    - dcd
build      : |
    dub build --build=release-debug --parallel
install    : |
    install -Dm00755 $workdir/serve-d $installdir/usr/bin/serve-d
