name       : serve-d
version    : 0.7.4
release    : 1
source     :
    - https://github.com/Pure-D/serve-d/archive/refs/tags/v0.7.4.tar.gz : 7d8f7d5017709270bbfe2b0dfd231ec04ad2c3ee8a0708fb4d09b52ddf1423fa
license    : MIT
component  : programming.tools
summary    : D LSP server (dlang language server protocol server)
description: |
    Microsoft language server protocol implementation for D. This program is the heart of code-d and implements most IDE features in D. The purpose of this project is to give every editor the same capabilities and editing features as code-d through the widely available Microsoft Language Server Protocol (LSP).
networking : yes
builddeps  :
    - dub
    - dmd
    - ldc-devel
build      : |
    dub build --build=release --compiler=ldc2
install    : |
    install -Dm00755 $workdir/serve-d $installdir/usr/bin/serve-d
